name: build-action

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-linux-xanmod"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/linux-xanmod.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          cd linux-xanmod
          patch -N -i ../pkgbuild.patch
          curl -L https://raw.githubusercontent.com/hamadmarri/TT-CPU-Scheduler/master/patches/6.0/tt-6.0.patch -o tt.patch
          patch -N -i ../ttpatch.patch
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.0/0013-optimize_harder_O3.patch -o O3.patch
      - name: Build kernel
        run: |
          cd linux-xanmod
          sed -i 's/a09ea05ed7bbdf80e96643404094080092d217882537bd54ea8437001ef2d24d/f3c82c80998afe76ab6616f9dcaff79da8d37c8b81ecc4af5b4f2f4af33d9516/g' PKGBUILD
          sed -i 's/pkgver=${_major}.11/pkgver=${_major}.12/g' PKGBUILD
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" env use_numa=n use_tracers=n makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
