name: build-action

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-linux-xanmod"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/linux-xanmod.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          cd linux-xanmod
          curl -LO https://github.com/xanmod/linux/releases/download/6.1.1-xanmod1/patch-6.1.1-xanmod1.xz
          export NEW=$(sha256sum patch-6.1.1-xanmod1.xz | awk '{ print $1}')
          curl -LO https://github.com/xanmod/linux/releases/download/6.1.0-xanmod1/patch-6.1.0-xanmod1.xz
          export OLD=$(sha256sum patch-6.1.0-xanmod1.xz | awk '{ print $1}')
          sed -i 's/${OLD}/${NEW}/g' PKGBUILD
          grep ${NEW} PKGBUILD
          sed -i 's/pkgver=${_major}.0/pkgver=${_major}.1/g' PKGBUILD
          patch -N -i ../pkgbuild.patch
          curl -L https://raw.githubusercontent.com/hamadmarri/TT-CPU-Scheduler/master/patches/6.1/tt-6.1.patch -o tt.patch
          patch -N -i ../ttpatch.patch
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.1/0013-optimize_harder_O3.patch -o O3.patch
      - name: Build kernel
        run: |
          cd linux-xanmod
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" env use_numa=n use_tracers=n makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
