name: build-linux-xanmod-eevdf-bore

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/linux-xanmod-eevdf-bore"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3    
      - name: Checkount linux-xanmod-bore repo
        uses: actions/checkout@v3
        with: 
          repository: micros24/linux-xanmod-bore
          ref: 6.4
          path: linux-xanmod-bore
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          cd linux-xanmod-bore
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.5/0003-eevdf.patch -o 0001-EEVDF.patch
          patch -N -i ../eevdfpatch.patch 
          sed -i '/echo "Setting version..."/i \ \ patch -Np1 -i ../../0001-EEVDF.patch' PKGBUILD
          sed -i '/echo "Setting version..."/i \ \ patch -Np1 -i ../../../fair.patch' PKGBUILD
          export OLD=$(sha256sum 0005-o3-optimization.patch | awk '{ print $1}')
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.5/0013-optimize_harder_O3.patch -o 0005-o3-optimization.patch
          export NEW=$(sha256sum 0005-o3-optimization.patch | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          export OLD=$(sha256sum 0001-bore.patch | awk '{ print $1}')
          curl -L https://raw.githubusercontent.com/firelzrd/bore-scheduler/main/patches/linux-6.5-eevdf-bore/0001-linux6.5.y-eevdf-bore3.1.3.patch -o 0001-bore.patch
          export NEW=$(sha256sum 0001-bore.patch | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          sed -i '/0002-constgran-vanilla-max/d' PKGBUILD
          sed -i '/0003-glitched-cfs/d' PKGBUILD
          sed -i '/0004-glitched-cfs-additions/d' PKGBUILD
          sed -i 's/pkgbase=linux-xanmod-bore/pkgbase=linux-xanmod-eevdf-bore/g' PKGBUILD
          curl -LO https://sourceforge.net/projects/xanmod/files/releases/edge/6.5.1-xanmod1/patch-6.5.1-xanmod1.xz
          export NEW=$(sha256sum patch-6.5.1-xanmod1.xz | awk '{ print $1}')
          curl -LO https://sourceforge.net/projects/xanmod/files/releases/main/6.4.14-xanmod1/patch-6.4.14-xanmod1.xz
          export OLD=$(sha256sum patch-6.4.14-xanmod1.xz | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.4.tar.xz
          export OLD=$(sha256sum linux-6.4.tar.xz | awk '{ print $1}')
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.5.tar.xz
          export NEW=$(sha256sum linux-6.5.tar.xz | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          sed -i 's/_major=6.4/_major=6.5/g' PKGBUILD
          sed -i 's/releases\/main/releases\edge/g' PKGBUILD
          sed -i 's/pkgver=${_major}.14/pkgver=${_major}.1/g' PKGBUILD
      - name: Build
        run: |
          cd linux-xanmod-bore
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
#          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod-eevdf-bore
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
