name: build-linux-xanmod-bore

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/linux-xanmod-bore"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3    
      - name: Checkount linux-xanmod-bore repo
        uses: actions/checkout@v3
        with: 
          repository: micros24/linux-xanmod-bore
          ref: 6.4
          path: linux-xanmod-bore
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
#      - name: Apply patches
#        run: |
#          cd linux-xanmod-bore
#          export OLD=$(sha256sum 0001-bore.patch | awk '{ print $1}')
#          curl -L https://raw.githubusercontent.com/firelzrd/bore-scheduler/main/bore-stable/0001-linux6.4.y-bore3.1.0.patch -o 0001-bore.patch
#          patch -N -i ../borepatch.patch 
#          export NEW=$(sha256sum 0001-bore.patch | awk '{ print $1}')
#          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
      - name: Build
        run: |
          cd linux-xanmod-bore
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
#          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod-bore
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
