name: build-linux-xanmod

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-linux-xanmod"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/linux-xanmod.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          cd linux-xanmod
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.5/0013-optimize_harder_O3.patch -o O3.patch
          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../O3.patch' PKGBUILD
          sed -i '/scripts\/config --enable CONFIG_STACK_VALIDATION/i \ \ scripts/config --disable CONFIG_HZ_500' PKGBUILD
          sed -i '/scripts\/config --enable CONFIG_STACK_VALIDATION/i \ \ scripts/config --enable CONFIG_HZ_1000' PKGBUILD
          curl -LO https://sourceforge.net/projects/xanmod/files/releases/edge/6.5.0-xanmod1/patch-6.5.0-xanmod1.xz
          export NEW=$(sha256sum patch-6.5.0-xanmod1.xz | awk '{ print $1}')
          curl -LO https://sourceforge.net/projects/xanmod/files/releases/main/6.4.12-xanmod1/patch-6.4.12-xanmod1.xz
          export OLD=$(sha256sum patch-6.4.12-xanmod1.xz | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.4.tar.xz
          export OLD=$(sha256sum linux-6.4.tar.xz | awk '{ print $1}')
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.5.tar.xz
          export NEW=$(sha256sum linux-6.5.tar.xz | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          sed -i 's/_major=6.4/_major=6.5/g' PKGBUILD
          sed -i 's/releases\/main/releases\edge/g' PKGBUILD
          sed -i 's/pkgver=${_major}.12/pkgver=${_major}.0/g' PKGBUILD
      - name: Build kernel
        run: |
          cd linux-xanmod
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" env use_numa=n use_tracers=n makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
