name: build-linux-xanmod-evdf-bore

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/linux-xanmod-evdf-bore"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3    
      - name: Checkount linux-xanmod-bore repo
        uses: actions/checkout@v3
        with: 
          repository: micros24/linux-xanmod-bore
          ref: 6.4
          path: linux-xanmod-bore
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          cd linux-xanmod-bore
          curl -L https://github.com/firelzrd/bore-scheduler/raw/main/eevdf-bore-dev/0001-linux6.4.y-eevdf-bore3.1.2.patch -o 0001-EEVDF.patch
          patch -N -i ../eevdfpatch.patch 
          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../0001-EEVDF.patch' PKGBUILD
          export OLD=$(sha256sum 0001-bore.patch | awk '{ print $1}')
          curl -L https://github.com/firelzrd/bore-scheduler/raw/main/eevdf-bore-dev/0001-linux6.4.y-eevdf-bore3.1.2.patch -o 0001-bore.patch
          patch -N -i ../eevdfborepatch.patch 
          export NEW=$(sha256sum 0001-bore.patch | awk '{ print $1}')
          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          sed -i 's/pkgbase=linux-xanmod-bore/pkgbase=linux-xanmod-evdf-bore/g' PKGBUILD
      - name: Build
        run: |
          cd linux-xanmod-bore
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm -sc" 
#          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod-evdf-bore
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
