name: build-linux-xanmod-tt

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-linux-xanmod-tt"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          git clone https://aur.archlinux.org/linux-xanmod.git
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        run: |
          cd linux-xanmod
          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.4/0013-optimize_harder_O3.patch -o O3.patch
          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../O3.patch' PKGBUILD
          sed -i '/scripts\/config --enable CONFIG_STACK_VALIDATION/i \ \ scripts/config --disable CONFIG_HZ_500' PKGBUILD
          sed -i '/scripts\/config --enable CONFIG_STACK_VALIDATION/i \ \ scripts/config --enable CONFIG_HZ_1000' PKGBUILD
          curl -L https://raw.githubusercontent.com/CachyOS/kernel-patches/master/6.4/sched/0001-tt.patch -o tt.patch
          patch -N -i ../ttpatch.patch
          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../tt.patch' PKGBUILD
          sed -i 's/pkgbase=linux-xanmod/pkgbase=linux-xanmod-tt/g' PKGBUILD
          curl -LO https://github.com/micros24/linux-xanmod-bore/raw/6.4/0004-glitched-cfs-additions.patch
          curl -LO https://github.com/micros24/linux-xanmod-bore/raw/6.4/0003-glitched-cfs.patch
          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../0003-glitched-cfs.patch' PKGBUILD
          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../0004-glitched-cfs-additions.patch' PKGBUILD
#          sed -i 's/pkgver=${_major}.5/pkgver=${_major}.6/g' PKGBUILD
#          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/incr/patch-6.4.5-6.xz
#          xz -d patch-6.4.5-6.xz
#          sed -i '/msg2 "Setting version..."/i \ \ patch -Np1 -i ../../patch-6.4.5-6' PKGBUILD
#          sed -i 's/${pkgver}-xanmod/6.4.5-xanmod/g' PKGBUILD
#          curl -LO https://github.com/xanmod/linux/releases/download/6.4.5-xanmod1/patch-6.4.5-xanmod1.xz
#          export NEW=$(sha256sum patch-6.4.5-xanmod1.xz | awk '{ print $1}')
#          curl -LO https://github.com/xanmod/linux/releases/download/6.4.4-xanmod1/patch-6.4.4-xanmod1.xz
#          export OLD=$(sha256sum patch-6.4.4-xanmod1.xz | awk '{ print $1}')
#          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#          sed -i 's/pkgrel=2/pkgrel=${xanmod}/g' PKGBUILD
#          sed -i 's/xanmod=2/xanmod=1/g' PKGBUILD
#          sed -i 's/_major=6.3/_major=6.4/g' PKGBUILD
#          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.4.tar.xz
#          export NEW=$(sha256sum linux-6.4.tar.xz | awk '{ print $1}')
#          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.3.tar.xz
#          export OLD=$(sha256sum linux-6.3.tar.xz | awk '{ print $1}')
#          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
      - name: Build kernel
        run: |
          cd linux-xanmod
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" env use_numa=n use_tracers=n makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: linux-xanmod
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
