name: build-linux-xanmod-bore

on:
  workflow_dispatch:
    inputs:
      apply_patch:
        type: boolean
        required: true
        description: "Apply patch flag"
      new_kernel_ver:
        type: string
        required: false
        description: "New kernel version"
      new_bore_ver:
        type: string
        required: false
        description: "New BORE version"
        
env:
  PKGDEST: "/tmp/linux-xanmod-bore"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4 
      - name: Checkount linux-xanmod-bore repo
        uses: actions/checkout@v4
        with: 
          repository: micros24/linux-xanmod-bore
          ref: 6.7
          path: linux-xanmod-bore
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo git
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown builder -R ..
          chown builder -R /tmp
          su builder -c "gpg --recv 38DBBDC86092693E"
      - name: Apply patches
        if: ${{ github.event.inputs.apply_patch == 'true' }}
        run: |
          cd linux-xanmod-bore
          sed -i 's/make INSTALL_MOD_PATH/# make INSTALL_MOD_PATH/g' PKGBUILD
          sed -i '/echo "Installing modules..."/a \ \ \ \ DEPMOD=/doesnt/exist modules_install  # Suppress depmod' PKGBUILD
          sed -i '/echo "Installing modules..."/a \ \ ZSTD_CLEVEL=19 make INSTALL_MOD_PATH="$pkgdir/usr" INSTALL_MOD_STRIP=1 \\' PKGBUILD
          if [ "${{ github.event.inputs.new_bore_ver }}" != "" ]; then
            export OLD=$(sha256sum 0001-bore.patch | awk '{ print $1}')
            curl -L https://raw.githubusercontent.com/firelzrd/bore-scheduler/main/patches/linux-6.7-bore/0001-linux6.7.y-bore${{ github.event.inputs.new_bore_ver }}.patch -o 0001-bore.patch 
            export NEW=$(sha256sum 0001-bore.patch | awk '{ print $1}')
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
            sed -i '/echo "Setting version..."/i \ \ patch -Np1 -i ../../../fair.patch' PKGBUILD
          fi
          PKGVERSION=$(grep "pkgver=" PKGBUILD)
          OLDVERSION="${PKGVERSION#*"."}"
          if [ "${{ github.event.inputs.new_kernel_ver }}" != "" ] && [ "${{ github.event.inputs.new_kernel_ver }}" != ${OLDVERSION} ]; then
            curl -LO https://sourceforge.net/projects/xanmod/files/releases/edge/6.7.${{ github.event.inputs.new_kernel_ver }}-xanmod1/patch-6.7.${{ github.event.inputs.new_kernel_ver }}-xanmod1.xz
            export NEW=$(sha256sum patch-6.7.${{ github.event.inputs.new_kernel_ver }}-xanmod1.xz | awk '{ print $1}')
            curl -LO https://sourceforge.net/projects/xanmod/files/releases/edge/6.7.${OLDVERSION}-xanmod1/patch-6.7.${OLDVERSION}-xanmod1.xz
            export OLD=$(sha256sum patch-6.7.${OLDVERSION}-xanmod1.xz | awk '{ print $1}')
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
            echo "sed -i 's/pkgver=\${_major}."${OLDVERSION}"/pkgver=\${_major}."${{ github.event.inputs.new_kernel_ver }}"/g' PKGBUILD" | bash
          fi
#            export OLD=$(sha256sum 0002-o3-optimization.patch | awk '{ print $1}')
#            curl -L https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.7/0013-optimize_harder_O3.patch -o 0002-o3-optimization.patch
#            export NEW=$(sha256sum 0002-o3-optimization.patch | awk '{ print $1}')
#            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#            curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.tar.xz
#            export OLD=$(sha256sum linux-6.6.tar.xz | awk '{ print $1}')
#            curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.7.tar.xz
#            export NEW=$(sha256sum linux-6.7.tar.xz | awk '{ print $1}')
#            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#          sed -i 's/sourceforge.net\/projects\/xanmod\/files\/releases\/main/master.dl.sourceforge.net\/project\/xanmod\/releases\/edge/g' PKGBUILD
#          curl -LO https://sourceforge.net/projects/xanmod/files/releases/main/6.6.${{ github.event.inputs.new_kernel_ver }}-xanmod1/patch-6.6.${{ github.event.inputs.new_kernel_ver }}-xanmod1.xz
#          sed -i '/# Setting HZ tick rate/a \ \ scripts/config --disable CONFIG_DRM_NOUVEAU' PKGBUILD
#          sed -i 's/releases\/edge/releases\/main/g' PKGBUILD
#          export OLD=$(sha256sum 0005-o3-optimization.patch | awk '{ print $1}')
#          curl -L https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/6.6/0013-optimize_harder_O3.patch -o 0005-o3-optimization.patch
#          export NEW=$(sha256sum 0005-o3-optimization.patch | awk '{ print $1}')
#          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#          export OLD=$(sha256sum 0001-bore.patch | awk '{ print $1}')
#          curl -L https://raw.githubusercontent.com/firelzrd/bore-scheduler/main/patches/linux-6.6-bore/0001-linux6.6.y-bore3.4.0.patch -o 0001-bore.patch 
#          export NEW=$(sha256sum 0001-bore.patch | awk '{ print $1}')
#          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#          sed -i '/0002-constgran-vanilla-max/d' PKGBUILD
#          sed -i '/0003-glitched-cfs/d' PKGBUILD
#          sed -i '/0004-glitched-cfs-additions/d' PKGBUILD
#          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.5.tar.xz
#          export OLD=$(sha256sum linux-6.5.tar.xz | awk '{ print $1}')
#          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.tar.xz
#          export NEW=$(sha256sum linux-6.6.tar.xz | awk '{ print $1}')
#          echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#          sed -i 's/_major=6.5/_major=6.6/g' PKGBUILD
#          sed -i 's/sourceforge.net\/projects/master.dl.sourceforge.net\/project/g' PKGBUILD
#          sed -i 's/rm "$_modulesdir"/rm -f "$_modulesdir"/g' PKGBUILD
#          curl -LO https://github.com/firelzrd/bore-scheduler/raw/main/patches/linux-6.5-eevdf-bore/0001-EEVDF.patch
#          patch -N -i ../eevdfpatch.patch 
#          sed -i '/echo "Setting version..."/i \ \ patch -Np1 -i ../../0001-EEVDF.patch' PKGBUILD
#          curl -L https://raw.githubusercontent.com/firelzrd/bore-scheduler/9e175253c03ac13cc493b728a3ee1637bdc15950/patches/linux-6.5-eevdf-bore/0002-linux6.5.y-eevdf-bore3.2.8.patch -o 0001-bore.patch 
#          patch -N -i ../borepatch.patch
      - name: Build
        run: |
          cd linux-xanmod-bore
          su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" env _compress_modules=y _use_numa=y _use_tracers=n makepkg --noconfirm -sc" 
#          su builder -c "yes '' | makepkg --noconfirm -sc"
      - uses: actions/upload-artifact@v4
        with:
          name: linux-xanmod-bore
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
