name: build-linux-xanmod-bore

on:
  workflow_dispatch:
    inputs:
      use_edge:
        type: boolean
        required: false
        description: "Use edge"
      new_kernel_minor_ver:
        type: string
        required: false
        description: "New kernel minor version"
      new_kernel_patch_ver:
        type: string
        required: false
        description: "New kernel patch version"
      bore_repository:
        type: boolean
        required: false
        description: "Use BORE repository"
      xanmod:
        type: string
        required: false
        description: "Xanmod release number"
jobs:
  build:
    runs-on: ubuntu-latest
#    container: archlinux:latest    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout bore repo
        uses: actions/checkout@v4
        with:
          repository: 'firelzrd/bore-scheduler'
          path: bore
      - name: Cleanup
#        if: ${{ 'true' == 'false' }}
        run: |
          sh ./cleanup.sh
      - name: Checkount linux-xanmod-bore repo
        uses: actions/checkout@v4
        with: 
          repository: micros24/linux-xanmod-bore
          ref: "6.16"
          path: linux-xanmod-bore
      - name: Apply patches
        run: |
          cd linux-xanmod-bore
          sed -i '/scripts\/config --enable STACK_VALIDATION/a \ \ scripts\/config --set-val CONFIG_X86_64_VERSION 2' PKGBUILD
          sed -i '/scripts\/config --enable STACK_VALIDATION/a \ \ scripts\/config --set-val CONFIG_LOCALVERSION "-x64v2"' PKGBUILD
          BRANCH=$(grep "_sf_branch=" PKGBUILD)
          OLDBRANCH="${BRANCH#_sf_branch=}"
          BRANCH="main"
          if [ "${{ github.event.inputs.use_edge }}" == "true" ]; then
            sed -i 's/_sf_branch=main/_sf_branch=edge/g' PKGBUILD
            BRANCH="edge"
          fi
          PKGVERSION=$(grep "pkgver=" PKGBUILD)
          OLDPATCHVERSION="${PKGVERSION#*"."}"
          MAJOR=$(grep "_major=" PKGBUILD)
          OLDVERSION="${MAJOR#_major=}"
          OLDMINORVERSION="${MAJOR#*.}"
          MINORVERSION=${OLDMINORVERSION}
          XANMOD=$(grep "xanmod=" PKGBUILD)
          OLDXANMOD="${XANMOD#*"."}"

          if [ "${{ github.event.inputs.xanmod }}" != "" ] && [ "${{ github.event.inputs.xanmod }}" != ${OLDXANMOD} ]; then
            export OLD=$(echo "xanmod="${OLDXANMOD})
            export NEW=$(echo "xanmod="${{ github.event.inputs.xanmod }})
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          fi

          if [ "${{ github.event.inputs.new_kernel_minor_ver }}" != "" ] && [ "${{ github.event.inputs.new_kernel_minor_ver }}" != ${OLDMINORVERSION} ]; then
            MINORVERSION="${{ github.event.inputs.new_kernel_minor_ver }}"
          fi
          if [ ${{ github.event.inputs.new_kernel_minor_ver }} != ${OLDMINORVERSION} ]; then
            curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.${{ github.event.inputs.new_kernel_minor_ver }}.tar.xz
            export NEW=$(sha256sum linux-6.${{ github.event.inputs.new_kernel_minor_ver }}.tar.xz | awk '{ print $1}')
            curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${OLDVERSION}.tar.xz
            export OLD=$(sha256sum linux-${OLDVERSION}.tar.xz | awk '{ print $1}')
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
            echo "sed -i 's/_major=${OLDVERSION}/_major=6.${{ github.event.inputs.new_kernel_minor_ver }}/g' PKGBUILD" | bash
            export OLD=$(sha256sum 0004-glitched-eevdf-additions.patch | awk '{ print $1}')
            sed -i 's/const_debug/__read_mostly/g' 0004-glitched-eevdf-additions.patch
            export NEW=$(sha256sum 0004-glitched-eevdf-additions.patch | awk '{ print $1}')
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          fi

          if [ "${{ github.event.inputs.bore_repository }}" == "true" ]; then
            export OLD=$(sha256sum 0001-bore.patch | awk '{ print $1}')
            cp ../bore/patches/stable/linux-6.${MINORVERSION}-bore/0001-linux*-bore-*.patch ./0001-bore.patch
            sed -i -e 's/scaling = SCHED_TUNABLESCALING_LOG/scaling = SCHED_TUNABLESCALING_NONE/' ./0001-bore.patch
            export NEW=$(sha256sum 0001-bore.patch | awk '{ print $1}')
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
          fi
          if  [ "${{ github.event.inputs.new_kernel_patch_ver }}" != "" ] && [ "${{ github.event.inputs.new_kernel_patch_ver }}" != ${OLDPATCHVERSION} ]; then
            curl -LO https://sourceforge.net/projects/xanmod/files/releases/${BRANCH}/6.${MINORVERSION}.${{ github.event.inputs.new_kernel_patch_ver }}-xanmod1/patch-6.${MINORVERSION}.${{ github.event.inputs.new_kernel_patch_ver }}-xanmod1.xz
            export NEW=$(sha256sum patch-6.${MINORVERSION}.${{ github.event.inputs.new_kernel_patch_ver }}-xanmod1.xz | awk '{ print $1}')
            curl -LO https://sourceforge.net/projects/xanmod/files/releases/${OLDBRANCH}/${OLDVERSION}.${OLDPATCHVERSION}-xanmod1/patch-${OLDVERSION}.${OLDPATCHVERSION}-xanmod1.xz
            export OLD=$(sha256sum patch-${OLDVERSION}.${OLDPATCHVERSION}-xanmod1.xz | awk '{ print $1}')
            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
            echo "sed -i 's/pkgver=\${_major}."${OLDPATCHVERSION}"/pkgver=\${_major}."${{ github.event.inputs.new_kernel_patch_ver }}"/g' PKGBUILD" | bash
          fi
#            export OLD=$(sha256sum 0002-glitched-cfs.patch | awk '{ print $1}')
#            curl -L https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.${MINORVERSION}/0003-glitched-cfs.patch -o 0002-glitched-cfs.patch
#            export NEW=$(sha256sum 0002-glitched-cfs.patch | awk '{ print $1}')
#            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#            export OLD=$(sha256sum 0003-glitched-eevdf-additions.patch | awk '{ print $1}')
#            curl -L https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.${MINORVERSION}/0003-glitched-eevdf-additions.patch -o 0003-glitched-eevdf-additions.patch
#            export NEW=$(sha256sum 0003-glitched-eevdf-additions.patch | awk '{ print $1}')
#            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
#            export OLD=$(sha256sum 0004-o3-optimization.patch | awk '{ print $1}')
#            curl -L https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.${MINORVERSION}/0013-optimize_harder_O3.patch -o 0004-o3-optimization.patch
#            export NEW=$(sha256sum 0004-o3-optimization.patch | awk '{ print $1}')
#            echo "sed -i 's/${OLD}/${NEW}/g' PKGBUILD" | bash
      - name: Set UserID
        run: |
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
        env: 
          USERID: ''          
      - name: Build
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./build-bore.sh ${{ env.USERID }} 
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-xanmod-bore
          path: ${{ github.workspace }}/linux-xanmod-bore/*.pkg.tar.zst
        
